KAIRScares 09-17-2020
GTBitsOfGood/bootcamp pull request #24
Opened 2020-09-17 23:55 UTC by ruchipatel1

2020-09-17 23:58 UTC, stephanieluo18 approved these changes
looks gucci

2020-09-18 00:06 UTC, nidhishad commented
looks good!

2020-09-20 22:32 UTC, Arthelon requested changes
Looks good! just delete that extraneous `foo` file

2020-09-20 22:32 UTC, Arthelon commented on foo
> +Hello World! hello
Please delete this file!

2020-09-20 23:59 UTC, Arthelon approved these changes

2020-09-20 23:59 UTC, merged